Update commit logic to use the new format.
dgraph-io/dgraph-js-http pull request #11
Opened 2019-02-16 01:17 UTC by martinmr

This change changes the format of the data passed to the commit endpoint
to include the list of preds.

Also updates the port to the port of the test cluster and removes a test
that is not compatible with the change.

2019-02-16 01:33 UTC, martinmr commented
This is failing because the version that the script installs does not have the changes yet. We need to wait until those changes are in the latest official release to be able to merge these changes.

2019-03-01 15:20 UTC, paulftw requested changes
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11)* status: 2 of 5 files reviewed, 4 unresolved discussions (waiting on @martinmr and @paulftw)

___
*[lib/clientStub.js, line 78 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZtpViiARPsbBqtzWsV:-LZtpVij4SfHe6LPWU5r:ba4ss5y) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/lib/clientStub.js#L78)):*
> ```JavaScript
>     };
>     DgraphClientStub.prototype.commit = function (ctx) {
>         var reqMap = {};
> ```

Is this a generated file or duplicated code? See comment below about the reqMap.
___
*[src/clientStub.ts, line 107 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZtntHPAKaoYDWe10Bd:-LZtntHPAKaoYDWe10Be:blqkh6m) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/src/clientStub.ts#L107)):*
> ```XML
>         const preds = "preds";
> 
>         if (ctx.keys == null) {
> ```

idiomatic javascript for constructing this reqMap is:
```
const reqMap = {
  keys: ctx.keys || [],
  preds: ctx.preds || [],
}
```
no need for any extra consts and if-branches. Please rewrite.
___
*[src/clientStub.ts, line 119 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZto_d42Cr6yKS7jNgR:-LZto_d42Cr6yKS7jNgS:b-21o2dr) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/src/clientStub.ts#L119)):*
> ```XML
>         }
> 
>         const body = JSON.stringify(reqMap);
> ```

I think it's OK to inline this expression as body isn't used elsewhere. 

Also a good idea to check maybe callAPI will do JSON.stringify when an object is passed instead of a string.
___
*[tests/helper.ts, line 3 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZtpo9_7u2Tev_bPYHi:-LZtpo9_7u2Tev_bPYHj:b-8vote5) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/tests/helper.ts#L3)):*
> ```XML
> import * as dgraph from "../src";
> 
> export const SERVER_ADDR = "http://localhost:8180"; // tslint:disable-line no-http-string
> ```

I don't see a corresponding change of the server config in this PR. Is this change specific to your machine?


<!-- Sent from Reviewable.io -->

2019-04-17 20:35 UTC, martinmr reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @paulftw)

___
*[lib/clientStub.js, line 78 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZtpViiARPsbBqtzWsV:-LcghTco6hTD57Tqv7Ug:b-gonihk) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/lib/clientStub.js#L78)):*
<details><summary><i>Previously, paulftw (Paul Korzhyk) wrote…</i></summary><blockquote>

Is this a generated file or duplicated code? See comment below about the reqMap.
</blockquote></details>

Yes, this is generated code
___
*[src/clientStub.ts, line 107 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZtntHPAKaoYDWe10Bd:-LcghSYu38acFefj0ifl:b-cu9nnp) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/src/clientStub.ts#L107)):*
<details><summary><i>Previously, paulftw (Paul Korzhyk) wrote…</i></summary><blockquote>

idiomatic javascript for constructing this reqMap is:
```
const reqMap = {
  keys: ctx.keys || [],
  preds: ctx.preds || [],
}
```
no need for any extra consts and if-branches. Please rewrite.
</blockquote></details>

The linter was complaining (ctx.keys is not a real boolean so it shouldn't be used that way) but I managed to do something similar.
___
*[src/clientStub.ts, line 119 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZto_d42Cr6yKS7jNgR:-LcgzuCbD7uO86LFLlID:bjrygq5) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/src/clientStub.ts#L119)):*
<details><summary><i>Previously, paulftw (Paul Korzhyk) wrote…</i></summary><blockquote>

I think it's OK to inline this expression as body isn't used elsewhere. 

Also a good idea to check maybe callAPI will do JSON.stringify when an object is passed instead of a string.
</blockquote></details>

I tried but the compiler complains saying it needs a property name. I left it as is.
Passing reqMap directly to callAPI didn't work.
___
*[tests/helper.ts, line 3 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/11#-LZtpo9_7u2Tev_bPYHi:-Lcghrwx3Px_OTWnUNq_:b-t7acxe) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/f995ea45cb7b7aa55511ff94c6d6ec4998ddf317/tests/helper.ts#L3)):*
<details><summary><i>Previously, paulftw (Paul Korzhyk) wrote…</i></summary><blockquote>

I don't see a corresponding change of the server config in this PR. Is this change specific to your machine?
</blockquote></details>

We usually run the tests in a dgraph cluster with an offset (by convention 100) so that the tests don't run in a prod or non-testing cluster by default. That's why I made the change. It looks like the build script for this repo is doing the same.


<!-- Sent from Reviewable.io -->

2020-05-18 13:49 UTC, paulftw commented
This has fallen under the rug. Closing the PR without merging. 

I think this commit logic has been implemented in another commit, since the tests are green.

2020-05-18 13:49 UTC, closed without merging