Add  Running an Upsert
dgraph-io/dgraph-js-http pull request #13
Opened 2019-09-09 23:46 UTC by MichelDiz

Adding doc for  Upserts.

2019-09-09 23:56 UTC, martinmr approved these changes
Some minor comments but it <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13#-:-LoNS9HtE5PN8-LEUOtp:b2px8ns)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @MichelDiz)

___
*[README.md, line 234 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13#-LoNRmBQ1KtVrnpiccVb:-LoNRmBQ1KtVrnpiccVc:b20w542) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/ee195cce8fefc97b96f5a82693fdebc479014a28/README.md#L234)):*
> ```
> runs a mutation and also upsert transactions.
> ```
"runs mutations and upsert transactions"
___
*[README.md, line 234 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13#-LoNS07SBY4FomHsBRxg:-LoNS07SBY4FomHsBRxh:bc4stqk) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/ee195cce8fefc97b96f5a82693fdebc479014a28/README.md#L234)):*
> ```
> provides two main ways to set data: JSON and RDF N-Quad.
> ```

"provides two data formats" ...


<!-- Sent from Reviewable.io -->

2019-09-09 23:56 UTC, martinmr reviewed
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13)* status: all files reviewed, 2 unresolved discussions (waiting on @MichelDiz)



<!-- Sent from Reviewable.io -->

2019-09-10 00:06 UTC, MichelDiz reviewed
> *[Reviewable](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @martinmr)

___
*[README.md, line 234 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13#-LoNRmBQ1KtVrnpiccVb:-LoNUVgX1veiqihVaAM_:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/ee195cce8fefc97b96f5a82693fdebc479014a28/README.md#L234)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

> ```
> runs a mutation and also upsert transactions.
> ```
"runs mutations and upsert transactions"
</blockquote></details>

Done.
___
*[README.md, line 234 at r1](https://reviewable.io/reviews/dgraph-io/dgraph-js-http/13#-LoNS07SBY4FomHsBRxg:-LoNUW-lDCEwVPNPISZQ:b-896fix) ([raw file](https://github.com/dgraph-io/dgraph-js-http/blob/ee195cce8fefc97b96f5a82693fdebc479014a28/README.md#L234)):*
<details><summary><i>Previously, martinmr (Martin Martinez Rivera) wrote…</i></summary><blockquote>

> ```
> provides two main ways to set data: JSON and RDF N-Quad.
> ```

"provides two data formats" ...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-09-10 17:19 UTC, mangalaman93 requested changes

2019-09-10 17:19 UTC, mangalaman93 commented on README.md
> +Txn#mutate(Mutation) runs mutations and upsert transactions. It takes in a Mutation object, which provides two data formats: JSON and RDF N-Quad. You can choose whichever way is convenient.
This doesn't seem right. @prashant-shahi please have a discussion about this with me. Something seems off.

2019-09-10 17:20 UTC, mangalaman93 commented on README.md
> +Txn#mutate(Mutation) runs mutations and upsert transactions. It takes in a Mutation object, which provides two data formats: JSON and RDF N-Quad. You can choose whichever way is convenient.
Please DO NOT MERGE.

2019-09-11 09:34 UTC, mangalaman93 commented
@MichelDiz closing this PR. More work needs to be done in this client. I didn't realize that the interface of the http client is similar to the grpc client. @prashant-shahi will work on this.

2019-09-11 09:34 UTC, closed without merging