chore: clean up repo
dgraph-io/dgraph-js-http pull request #71
Opened 2023-05-31 05:02 UTC by joshua-goldstein

Cleaning up repo and bringing it into more standard form.  WIP.

2023-05-31 12:11 UTC, mangalaman93 requested changes, later dismissed

2023-05-31 12:11 UTC, mangalaman93 commented on scripts/test.sh
> +sleep 10 # Dgraph need some time to create Groot user
we could hit the health endpoint instead

2023-05-31 12:11 UTC, mangalaman93 commented on scripts/test.sh
>  #!/bin/bash
instead of test.sh, it could run_test.sh or something. test.sh is very common name while doing some scratch work.

2023-06-01 07:03 UTC, joshua-goldstein commented on README.md
> -npm install dgraph-js-http --save
hasn't been needed in modern versions of npm for a long time, see https://stackoverflow.com/questions/19578796/what-is-the-save-option-for-npm-install

2023-06-02 07:55 UTC, all-seeing-code approved these changes

2023-06-02 07:57 UTC, merged